spring:
  datasource:
    url: jdbc:mysql://localhost/grupo15oo22020?serverTimezone=UTC
    username: root
    password: 
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
server:
  port : 9090